---
data_path: "/data/tina/Thomson/IN3O044052.isi"
mongo_db_name: "easiparse_test"
mongo_host: "localhost"
mongo_port: 27017
match_regexp: \bembryolog.+\b|\bembryo(s)?\b|\bembryonic.+\b
#match_regexp: to
isi:
    tag_length: 3
    multiline: "--"
    issues:
        key: "UI"
        begin: "UI"
        end: "RE"
        fields:
            UI: ""
            T1: ""
            PW: ""
            GA: ""
            SQ: ""
            PT: ""
            SO: ""
            JI: ""
            J1: ""
            J2: ""
            J9: ""
            CF: ~
            SC: ~
            SN: ""
            SC: ""
            BN: ""
            BS: ""
            PU: ""
            PI: ""
            PA: ""
            VL: ""
            IS: ""
            PY: ""
            PD: ""
            SU: ""
            SI: ""
            PN: ""
            TV: ""
            IL: ""
            LD: ""
            IO: ""
    items:
        key: "UT"
        begin: "UT"
        end: "EX"
        fields:
            UT: ""
            T9: ""  
            T2: ""
            AR: ~
            AU: ~
            RY: ""
            TI: ""
            DT: ""
            DE: ~
            LA: ""
            AB: ""
            AA: ""
            RY: int
        subfields:
            C1:
                fields:
                    NU: ""
                    NY: ""
                    NF: ""
                    NC : ""
                end:  "EA"
            CP:
                fields:
                    '/A': ""
                    '/Y': ""
                    '/W': ""
                    '/N': ""
                    '/C ': ""
                end:  "EC"
            CR:
                fields:
                    R9: ""
                    AR: ~
                    '/A': ""
                    '/Y': ""
                    '/W': ""
                    '/I': ""
                    'RS': ""
                    '/V': ""
                end: "EC"
extraction_fields:
    - "TI" 
    - "AB"
required_fields:
    - "TI"
output_file: "easiparse_output_test.isi.txt"
#output_file: "/data/tina/Thomson/mdts11_embryonics_wos_raw_20100214.isi.txt"
