---
data_path: "/data/tina/Thomson/*.isi"
mongo_db_name: "isi"
mongo_host: "localhost"
mongo_port: 27017
match_regexp: \bembryolog(y|ies)\b|\bembryo(s)?\b|\bembryonic(s)?\b
isi:
    begin: "UT"
    end: "EX"
    tag_length: 3
    multiline: "--"
    fields:
        #UT: ""
        T9: "" 
        T2: ""
        AR: ~
        AU: ~
        TI: ""
        DT: ""
        DE: ~
        LA: ""
        AB: ""
        AA: ""
    subfields:
        C1:
            fields:
                NU: ""
                NY: ""
                NF: ""
                NC: ""
            end: "EA"
        CP:
            fields:
                '/A': ""
                '/Y': ""
                '/W': ""
                '/N': ""
                '/C': ""
            end: "EC"
        CR:
            fields:
                R9: ""
                AR: ~
                '/A': ""
                '/Y': ""
                '/W': ""
                '/I': ""
            end : "EC"
        #AF 	ISIAF	$ligne$
        #J9 	ISIJOURNAL
        #RP 	ISIRP	,
        #FU 	ISIFU	;
        #TC 	ISITC
        #SO 	ISISO
        #PY 	ISIpubdate
        #VL 	ISIVolume
        #BP 	ISIPage
        #SC 	ISISC	;
extraction_fields:
    - "TI"
    - "AB"
required_fields:
    - "TI"
output_file: "/data/tina/Thomson/embryo_data.txt"